
# Translation before adding point cloud to the map
# TODO - see if setting this lower helps
# TODO - later - remove old parts of the point cloud to only keep a local map...
translation_threshold_kf: 1.0 # 1.0
# Tune this to be larger to avoid delays - map update and publishis expensive 
rotation_threshold_kf: 0.3 #0.3 # radians. 45 deg = 0.79

# Limit to print warning for time diff between point clouds
point_cloud_time_diff_limit: 0.11