b_verbose: false

translation_threshold_kf: 1.0 
rotation_threshold_kf: 0.3 

map_publishment: 
  b_publish_map: true
  meters: 1

queues: 
  lidar_queue_size: 1
  imu_queue_size: 10000
  odom_queue_size: 1000 
  pose_queue_size: 1000

buffers: 
  imu_buffer_size_limit: 1000
  odometry_buffer_size_limit: 1000
  pose_stamped_buffer_size_limit: 1000

# DATA INTEGRATION 
  # 0   ---> no integration 
  # 1   ---> imu integration 
  # 2   ---> imu yaw integration
  # 3   ---> odometry integration 
  # 4   ---> pose_stamped integration

data_integration: 
  mode: 3
  max_number_of_calls: 25