b_verbose: false

translation_threshold_kf: 1.0 
rotation_threshold_kf: 0.3 

number_of_points_open_space: 9999999 # Dsiabled - baseline to use is: 11000

map_publishment: 
  b_publish_map: true
  meters: 1

b_run_rolling_map_buffer: false

queues: 
  lidar_queue_size: 1
  imu_queue_size: 10000
  odom_queue_size: 1000 
  pose_queue_size: 1000

buffers: 
  imu_buffer_size_limit: 1000
  odometry_buffer_size_limit: 1000
  pose_stamped_buffer_size_limit: 1000

# DATA INTEGRATION 
  # 0   ---> no integration 
  # 1   ---> imu integration 
  # 2   ---> imu yaw integration
  # 3   ---> odometry integration 
  # 4   ---> pose_stamped integration

data_integration: 
  mode: 3
  max_number_of_calls: 25

b_is_flat_ground_assumption: false

b_enable_computation_time_profiling: false

b_run_with_gt_point_cloud: false
gt_point_cloud_filename: /home/costar/data/loeval/beta_both_floors.pcd

publish_diagnostics: false

msw_box_filter_size: 15