b_verbose: false
b_publish_map: true

translation_threshold_kf: 1.0 
rotation_threshold_kf: 0.3 

buffers: 
  imu_buffer_size_limit: 1000
  odometry_buffer_size_limit: 1000
  pose_stamped_buffer_size_limit: 1000

syncing: 
  ts_threshold: 0.1

imu_integration: 
  b_use_imu_integration: false
  b_use_imu_yaw_only: false
  imu_max_number_of_calls: 25

odometry_integration: 
  b_use_odometry_integration: false
  odometry_max_number_of_calls: 25

pose_stamped_integration:
  b_use_pose_stamped_integration: false
  pose_stamped_max_number_of_calls: 25

queue_sizes: 
  imu_queue_size: 10000
  odom_queue_size: 1000 
  pose_queue_size: 1000
  lidar_queue_size: 1

map_publishment: 
  meters: 1